apiVersion: skaffold/v2alpha3
kind: Config
deploy:
  kubectl:
    manifests:
      - ./infra/k8s/*
build:
  local:
    push: false
  artifacts:
    - image: mahmedmushtaq/auth
      context: auth
      docker:
        dockerfile: DockerFile
      sync:
        manual:
          - src: src/**/*.ts
            dest: .
    - image: mahmedmushtaq/client
      context: client
      docker:
        dockerfile: DockerFile
      sync:
        manual:
          - src: '**/*.js'
            dest: .
    - image: mahmedmushtaq/tickets
      context: tickets
      docker:
        dockerfile: DockerFile
      sync:
        manual:
          - src: src/**/*.ts
            dest: .
    - image: mahmedmushtaq/orders
      context: orders
      docker:
        dockerfile: DockerFile
      sync:
        manual:
          - src: src/**/*.ts
            dest: .
    - image: mahmedmushtaq/expiration
      context: expiration
      docker:
        dockerfile: DockerFile
      sync:
        manual:
          - src: src/**/*.ts
            dest: .

    - image: mahmedmushtaq/payments
      context: payments
      docker:
        dockerfile: DockerFile
      sync:
        manual:
          - src: src/**/*.ts
            dest: .
